apiVersion: v1
kind: ReplicationController
metadata:
  name: droneio
  labels:
    name: droneio
spec:
  replicas: 1
  selector:
    name: droneio
  template:
    metadata:
      labels:
        name: droneio
    spec:
      containers:
        - image: drone/drone:0.4
          name: droneio
          env:
            - name: SERVER_ADDR
              value: ":80"
            - name: DATABASE_DRIVER
              value: sqlite3
            - name: DATABASE_CONFIG
              value: /var/lib/drone/drone.sqlite
            - name: REMOTE_DRIVER
              value: gogs
            - name: REMOTE_CONFIG
              value: http://git.eko.ovh/?open=false
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/drone
              name: droneio-sqlite-db
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-lib
      volumes:
        - name: droneio-sqlite-db
          hostPath:
            path: /srv/droneio-sqlite
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /var/lib/docker
